blank_issues_enabled: false
contact_links:
  - name: Discussions - support questions and ideas
    url: https://github.com/j127/youtube_shorts_normal_player/discussions/new
    about: Support questions and feature ideas can be raised and discussed here.
